### ISSUE TITLE
UnifiedNlp crashes

### ISSUE THREAD

**Issue by sedrubal** [n76/wifi_backend#27]
Since I have updated from `0.9.91` to `1.0.0` (F-Droid) unifiedNlp crashes from time to time (the android alert "unifiedNlp stopped" appears) even if I did nothing...

**Comment by n76** [comment]
Interesting as the only difference between those two versions are changes in the Serbian language string resources. Do you have a logcat from when you get the "unifiedNlp stopped" message?

**Comment by sedrubal** [comment]
Mh ok that's weird :D I think this error appeared before, when I installed it the first time and enabled it... It may also be a error caused by "unifiedNlp" and not by wifi_backend...

Here is a logcat:

```adb
02-08 23:41:50.334   733   752 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@a6dd0de attribute=null, token = android.os.BinderProxy@c2a6990
02-08 23:41:50.338 15625 16381 D NlpLocBackendHelper: Unbinding from: Intent { act=org.microg.nlp.LOCATION_BACKEND pkg=org.fitchfamily.android.gsmlocation cmp=org.fitchfamily.android.gsmlocation/.GsmService }
02-08 23:41:50.340 15625 16381 D NlpLocBackendHelper: Unbinding from: Intent { act=org.microg.nlp.LOCATION_BACKEND pkg=org.fitchfamily.android.wifi_backend cmp=org.fitchfamily.android.wifi_backend/.backend.BackendService_ }
02-08 23:41:50.342 15625 16381 D NlpLocBackendHelper: Binding to: Intent { act=org.microg.nlp.LOCATION_BACKEND pkg=org.microg.nlp.backend.ichnaea cmp=org.microg.nlp.backend.ichnaea/.BackendService }
02-08 23:41:50.355   733 14542 I ActivityManager: Start proc 16382:org.microg.nlp.backend.ichnaea/u0a82 for service org.microg.nlp.backend.ichnaea/.BackendService
02-08 23:41:50.355 15625 16381 D NlpLocBackendHelper: Binding to: Intent { act=org.microg.nlp.LOCATION_BACKEND pkg=org.fitchfamily.android.gsmlocation cmp=org.fitchfamily.android.gsmlocation/.GsmService }
02-08 23:41:50.358 15625 16381 D NlpLocBackendHelper: Binding to: Intent { act=org.microg.nlp.LOCATION_BACKEND pkg=org.fitchfamily.android.wifi_backend cmp=org.fitchfamily.android.wifi_backend/.backend.BackendService_ }
02-08 23:41:50.363 15625 16389 D NlpLocBackendHelper: Not (yet) bound.
02-08 23:41:50.363 15625 16389 D NlpLocBackendHelper: Not (yet) bound.
02-08 23:41:50.363 15625 16389 D NlpLocBackendHelper: Not (yet) bound.
02-08 23:41:50.363 15625 15625 D NlpLocBackendHelper: Bound to: ComponentInfo{org.fitchfamily.android.gsmlocation/org.fitchfamily.android.gsmlocation.GsmService}
02-08 23:41:50.434 15625 16381 W SettingsInjector: Ignoring attempt to inject setting from app not in system image: ResolveInfo{87f0331 org.microg.nlp/.ui.SettingInjectorService m=0x0}
02-08 23:41:50.437 15625 15625 D NlpLocBackendHelper: Bound to: ComponentInfo{org.fitchfamily.android.wifi_backend/org.fitchfamily.android.wifi_backend.backend.BackendService_}
02-08 23:41:50.460 16382 16382 W System  : ClassLoader referenced unknown path: /data/app/org.microg.nlp.backend.ichnaea-1/lib/arm
02-08 23:41:50.465 15625 15625 D NlpLocBackendHelper: Bound to: ComponentInfo{org.microg.nlp.backend.ichnaea/org.microg.nlp.backend.ichnaea.BackendService}
02-08 23:41:50.471 15625 15680 E NlpLocationProvider: Exception
02-08 23:41:50.471 15625 15680 E NlpLocationProvider: java.lang.SecurityException: need INSTALL_LOCATION_PROVIDER permission, or UID of a currently bound location provider
02-08 23:41:50.471 15625 15680 E NlpLocationProvider:   at android.os.Parcel.readException(Parcel.java:1620)
02-08 23:41:50.471 15625 15680 E NlpLocationProvider:   at android.os.Parcel.readException(Parcel.java:1573)
02-08 23:41:50.471 15625 15680 E NlpLocationProvider:   at android.location.ILocationManager$Stub$Proxy.reportLocation(ILocationManager.java:1281)
02-08 23:41:50.471 15625 15680 E NlpLocationProvider:   at com.android.location.provider.LocationProviderBase.reportLocation(LocationProviderBase.java:136)
02-08 23:41:50.471 15625 15680 E NlpLocationProvider:   at org.microg.nlp.location.BackendFuser.updateLocation(BackendFuser.java:101)
02-08 23:41:50.471 15625 15680 E NlpLocationProvider:   at org.microg.nlp.location.BackendFuser.reportLocation(BackendFuser.java:131)
02-08 23:41:50.471 15625 15680 E NlpLocationProvider:   at org.microg.nlp.location.BackendHelper$Callback.report(BackendHelper.java:142)
02-08 23:41:50.471 15625 15680 E NlpLocationProvider:   at org.microg.nlp.api.LocationCallback$Stub.onTransact(LocationCallback.java:55)
02-08 23:41:50.471 15625 15680 E NlpLocationProvider:   at android.os.Binder.execTransact(Binder.java:453)
02-08 23:41:50.471 15625 15680 V NlpLocationBackendFuser: location=Location[network {my location} acc=4307 et=+7h59m40s55ms {Bundle[{noGPSLocation=Location[network {my location^^} acc=4307 et=+7h59m40s55ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService}]}]
02-08 23:41:50.473 16382 16382 D AndroidRuntime: Shutting down VM
02-08 23:41:50.473 16382 16382 E AndroidRuntime: FATAL EXCEPTION: main
02-08 23:41:50.473 16382 16382 E AndroidRuntime: Process: org.microg.nlp.backend.ichnaea, PID: 16382
02-08 23:41:50.473 16382 16382 E AndroidRuntime: java.lang.SecurityException: Neither user 10082 nor current process has android.permission.ACCESS_COARSE_LOCATION.
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenForSubscriber(ITelephonyRegistry.java:553)
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at android.telephony.TelephonyManager.listen(TelephonyManager.java:2685)
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at org.microg.nlp.api.CellBackendHelper.registerPhoneStateListener(CellBackendHelper.java:310)
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at org.microg.nlp.api.CellBackendHelper.access$400(CellBackendHelper.java:53)
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at org.microg.nlp.api.CellBackendHelper$1.run(CellBackendHelper.java:101)
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-08 23:41:50.473 16382 16382 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-08 23:41:50.474   733   845 D WifiService: New client listening to asynchronous messages
02-08 23:41:50.487 16382 16394 D IchnaeaBackendService: Activating instance at process 16382
02-08 23:41:50.489 15625 15625 E NlpLocationProvider: Exception
02-08 23:41:50.489 15625 15625 E NlpLocationProvider: java.lang.SecurityException: need INSTALL_LOCATION_PROVIDER permission, or UID of a currently bound location provider
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at android.os.Parcel.readException(Parcel.java:1620)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at android.os.Parcel.readException(Parcel.java:1573)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at android.location.ILocationManager$Stub$Proxy.reportLocation(ILocationManager.java:1281)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at com.android.location.provider.LocationProviderBase.reportLocation(LocationProviderBase.java:136)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at org.microg.nlp.location.BackendFuser.updateLocation(BackendFuser.java:101)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at org.microg.nlp.location.BackendFuser.reportLocation(BackendFuser.java:131)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:65)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at org.microg.nlp.location.BackendHelper.onServiceConnected(BackendHelper.java:123)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at android.os.Handler.handleCallback(Handler.java:739)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at android.os.Handler.dispatchMessage(Handler.java:95)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at android.os.Looper.loop(Looper.java:148)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at android.app.ActivityThread.main(ActivityThread.java:5417)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at java.lang.reflect.Method.invoke(Native Method)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-08 23:41:50.489 15625 15625 E NlpLocationProvider:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-08 23:41:50.490 15625 15625 V NlpLocationBackendFuser: location=Location[network {my location^^} acc=4307 et=+7h59m40s55ms {Bundle[{noGPSLocation=Location[network {my location^^} acc=4307 et=+7h59m40s55ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService}]}]
02-08 23:41:50.503   733   743 I art     : Background partial concurrent mark sweep GC freed 37727(2003KB) AllocSpace objects, 2(40KB) LOS objects, 30% free, 36MB/52MB, paused 1.011ms total 139.972ms
02-08 23:41:50.520   733 15190 I OpenGLRenderer: Initialized EGL, version 1.4
02-08 23:41:52.496 16382 16382 I Process : Sending signal. PID: 16382 SIG: 9
02-08 23:41:52.505   733   845 D WifiService: Client connection lost with reason: 4
02-08 23:41:52.505 15625 15625 D NlpLocBackendHelper: Unbound from: ComponentInfo{org.microg.nlp.backend.ichnaea/org.microg.nlp.backend.ichnaea.BackendService}
02-08 23:41:52.513   733  4601 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@d8a53bb attribute=null, token = android.os.BinderProxy@c2a6990
02-08 23:41:52.525   733  1303 I ActivityManager: Process org.microg.nlp.backend.ichnaea (pid 16382) has died
02-08 23:41:52.526   733  1303 W ActivityManager: Scheduling restart of crashed service org.microg.nlp.backend.ichnaea/.BackendService in 1000ms
02-08 23:41:52.615   733   768 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
02-08 23:41:53.038 16416 16416 D QSEECOMD: : qseecom listener services process entry PPID = 1
02-08 23:41:53.038 16416 16416 E QSEECOMD: : Listener: index = 0, hierarchy = 0
02-08 23:41:53.038 16416 16416 E QSEECOMD: : Init dlopen(librpmb.so, RLTD_NOW) is failed....
02-08 23:41:53.038 16416 16416 E QSEECOMD: : ERROR: RPMB_INIT failed, shall not start listener services
02-08 23:41:53.540   733   754 I ActivityManager: Start proc 16417:org.microg.nlp.backend.ichnaea/u0a82 for service org.microg.nlp.backend.ichnaea/.BackendService
02-08 23:41:53.576 16417 16417 W System  : ClassLoader referenced unknown path: /data/app/org.microg.nlp.backend.ichnaea-1/lib/arm
02-08 23:41:53.583 15625 15625 D NlpLocBackendHelper: Bound to: ComponentInfo{org.microg.nlp.backend.ichnaea/org.microg.nlp.backend.ichnaea.BackendService}
02-08 23:41:53.591 16417 16417 D AndroidRuntime: Shutting down VM
02-08 23:41:53.592 16417 16417 E AndroidRuntime: FATAL EXCEPTION: main
02-08 23:41:53.592 16417 16417 E AndroidRuntime: Process: org.microg.nlp.backend.ichnaea, PID: 16417
02-08 23:41:53.592 16417 16417 E AndroidRuntime: java.lang.SecurityException: Neither user 10082 nor current process has android.permission.ACCESS_COARSE_LOCATION.
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1620)
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1573)
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenForSubscriber(ITelephonyRegistry.java:553)
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at android.telephony.TelephonyManager.listen(TelephonyManager.java:2685)
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at org.microg.nlp.api.CellBackendHelper.registerPhoneStateListener(CellBackendHelper.java:310)
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at org.microg.nlp.api.CellBackendHelper.access$400(CellBackendHelper.java:53)
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at org.microg.nlp.api.CellBackendHelper$1.run(CellBackendHelper.java:101)
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-08 23:41:53.592 16417 16417 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-08 23:41:53.598   733   845 D WifiService: New client listening to asynchronous messages
02-08 23:41:53.611 16417 16428 D IchnaeaBackendService: Activating instance at process 16417
02-08 23:41:53.615   733 25727 D NetlinkSocketObserver: NeighborEvent{elapsedMs=28783201, 192.168.1.1, [6466B3C53662], RTM_NEWNEIGH, NUD_REACHABLE}
02-08 23:41:53.633   733 15190 I OpenGLRenderer: Initialized EGL, version 1.4
02-08 23:41:53.718   733   754 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{b1167fa u-1 android.net.wifi.SCAN_RESULTS} to ReceiverList{df38aee 16417 org.microg.nlp.backend.ichnaea/10082/u0 remote:813f069}: process crashing
02-08 23:41:53.721 15625 15636 E NlpLocationProvider: Exception
02-08 23:41:53.721 15625 15636 E NlpLocationProvider: java.lang.SecurityException: need INSTALL_LOCATION_PROVIDER permission, or UID of a currently bound location provider
02-08 23:41:53.721 15625 15636 E NlpLocationProvider:   at android.os.Parcel.readException(Parcel.java:1620)
02-08 23:41:53.721 15625 15636 E NlpLocationProvider:   at android.os.Parcel.readException(Parcel.java:1573)
02-08 23:41:53.721 15625 15636 E NlpLocationProvider:   at android.location.ILocationManager$Stub$Proxy.reportLocation(ILocationManager.java:1281)
02-08 23:41:53.721 15625 15636 E NlpLocationProvider:   at com.android.location.provider.LocationProviderBase.reportLocation(LocationProviderBase.java:136)
02-08 23:41:53.721 15625 15636 E NlpLocationProvider:   at org.microg.nlp.location.BackendFuser.updateLocation(BackendFuser.java:101)
02-08 23:41:53.721 15625 15636 E NlpLocationProvider:   at org.microg.nlp.location.BackendFuser.reportLocation(BackendFuser.java:131)
02-08 23:41:53.721 15625 15636 E NlpLocationProvider:   at org.microg.nlp.location.BackendHelper$Callback.report(BackendHelper.java:142)
02-08 23:41:53.721 15625 15636 E NlpLocationProvider:   at org.microg.nlp.api.LocationCallback$Stub.onTransact(LocationCallback.java:55)
02-08 23:41:53.721 15625 15636 E NlpLocationProvider:   at android.os.Binder.execTransact(Binder.java:453)
02-08 23:41:53.721 15625 15636 V NlpLocationBackendFuser: location=Location[network {my location} acc=4307 et=+7h59m40s55ms {Bundle[{noGPSLocation=Location[network {my location} acc=4307 et=+7h59m40s55ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService}]}]
02-08 23:41:55.656 16417 16417 I Process : Sending signal. PID: 16417 SIG: 9
02-08 23:41:55.665 15625 15625 D NlpLocBackendHelper: Unbound from: ComponentInfo{org.microg.nlp.backend.ichnaea/org.microg.nlp.backend.ichnaea.BackendService}
02-08 23:41:55.666   733   845 D WifiService: Client connection lost with reason: 4
02-08 23:41:55.670   733  1221 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@7c043a1 attribute=null, token = android.os.BinderProxy@c2a6990
02-08 23:41:55.677   733  1216 I ActivityManager: Process org.microg.nlp.backend.ichnaea (pid 16417) has died
02-08 23:41:55.677   733  1216 W ActivityManager: Service crashed 2 times, stopping: ServiceRecord{298c224 u0 org.microg.nlp.backend.ichnaea/.BackendService}
02-08 23:41:55.776   733   768 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
```

**Comment by n76** [comment]
The fatal exception is occurring on the ichnaea backend which is the Mozilla based one, not this wifi backend.

I have not see the other exception, INSTALL_LOCATION_PROVIDER, which is against the UnifiedNLP itself. What version of Android are you running? If 6.x, have you allowed appropriate permissions to UnifiedNLP (or GmsCore if using that)?

But in both cases, the errors don't seem to be in the local WiFi backend.

**Comment by sedrubal** [comment]
Mh sorry, I should have read this... :D

I use Android `6.0.1` and `Location` and `Telefone` permission for MozillaNlpBackend was turned off...

Thanks for debugging :+1:
